Defines read only mode behavior
RedHatProductSecurity/osim pull request #112
Opened 2024-03-19 17:58 UTC by superbuggy

2024-03-20 10:11 UTC, JakubFrejlach requested changes
Some observations and suggestions.

2024-03-20 10:11 UTC, JakubFrejlach commented on src/stores/osimRuntime.ts
> +  readOnly: z.boolean().default(false),
[docs](https://github.com/RedHatProductSecurity/osim/blob/feature/OSIDB-2317-read-only-mode/docs/overview.md#local-configuration) local config example should be refined to comply with the changes.

2024-03-20 10:11 UTC, JakubFrejlach commented on src/stores/osimRuntime.ts
> +      }
What is the purpose of this condition?

2024-03-20 10:13 UTC, JakubFrejlach commented
@superbuggy Also I've noticed that this branch is 10 commits behind the `main` but it does not reports any conflicts, which is really weird, because at least the `package.json` file removes again the lint functionality from the build command, there should be conflict reported at least. :thinking:

2024-03-20 14:21 UTC, superbuggy commented
> @superbuggy Also I've noticed that this branch is 10 commits behind the `main` but it does not reports any conflicts, which is really weird, because at least the `package.json` file removes again the lint functionality from the build command, there should be conflict reported at least. 🤔

It is common for feature branches to lag behind main, and in this case since that conflict was already resolved and there are no commits _unique to this branch_ to `package.json`, there are no conflicts, so it is expected that no conflicts be reported.

It wasn't clear if this was the change you were requested, if so, then no change is necessary as there is no conflict.

2024-03-21 10:42 UTC, JakubFrejlach commented on src/stores/osimRuntime.ts
> +      }
I see. Thank you.

2024-03-21 10:43 UTC, JakubFrejlach commented
> > @superbuggy Also I've noticed that this branch is 10 commits behind the `main` but it does not reports any conflicts, which is really weird, because at least the `package.json` file removes again the lint functionality from the build command, there should be conflict reported at least. 🤔
> 
> It is common for feature branches to lag behind main, and in this case since that conflict was already resolved and there are no commits _unique to this branch_ to `package.json`, there are no conflicts, so it is expected that no conflicts be reported.
> 
> It wasn't clear if this was the change you were requested, if so, then no change is necessary as there is no conflict.

My concern was that the linting is not yet again erased from the package.json scripts however you've already rebased that. My change request was more related to documenting the new example of runtime.json.

2024-03-28 13:08 UTC, JakubFrejlach approved these changes

2024-03-28 18:00 UTC, C-Valen approved these changes
Huddle reviewed. LGTM.

2024-03-28 18:03 UTC, tboyetteredhat approved these changes

2024-03-29 19:43 UTC, d10n approved these changes

2024-03-29 20:44 UTC, merged