OSIDB-2321: Removed trackers from create flaw form and added the unit tests too
RedHatProductSecurity/osim pull request #143
Opened 2024-04-04 12:52 UTC by alizard0

It removes the trackers section from the FlawForm when it is on CREATE mode only.

Implements https://issues.redhat.com/browse/OSIDB-2321

2024-04-04 12:55 UTC, alizard0 commented
A small comment for the reviewers, I am not sure if that's the best way to prove that the element is not rendered.

https://github.com/RedHatProductSecurity/osim/pull/143/files#diff-967a205363234f686e2f6df964ed2631bc6e26c2ba4f9d69abad87898d0d3461R276

2024-04-04 13:39 UTC, tboyetteredhat requested changes

2024-04-04 13:39 UTC, tboyetteredhat commented on src/components/__tests__/FlawForm.spec.ts
> +import LabelCollapsable from '../widgets/LabelCollapsable.vue'
We need to fix lint issue. 
![Screenshot from 2024-04-04 09-37-49](https://github.com/RedHatProductSecurity/osim/assets/156366006/a7b9fc73-c6ad-474e-a3eb-f1d173d25a0e)

2024-04-04 14:25 UTC, tboyetteredhat approved these changes

2024-04-04 14:48 UTC, JakubFrejlach approved these changes
I would recommend to squash these two commits into one and rebase it as such commits which tend to address syntax/linting/etc. are not really adding any value and git history will be much more readable without them. But just my personal preference.

2024-04-05 08:17 UTC, merged

2024-04-05 12:51 UTC, superbuggy commented
> I would recommend to squash these two commits into one and rebase it as such commits which tend to address syntax/linting/etc. are not really adding any value and git history will be much more readable without them. But just my personal preference.

To this point, formatting commits being in dedicated commits makes it possible to ignore them in git history by using an ignore revs file as in #125

2024-04-05 16:49 UTC, JakubFrejlach commented
> > I would recommend to squash these two commits into one and rebase it as such commits which tend to address syntax/linting/etc. are not really adding any value and git history will be much more readable without them. But just my personal preference.
> 
> 
> 
> To this point, formatting commits being in dedicated commits makes it possible to ignore them in git history by using an ignore revs file as in #125 

Yeah, but this is a different scenario. First commit here introduces the linting error, second commit here fixes the linting error. Having both these commits adds no value, better approach here is to just squash/fixup the commits so the linting error is never introduced in the first place.