OSIDB-2876:  Add new affected component button
RedHatProductSecurity/osim pull request #258
Opened 2024-06-10 17:33 UTC by tboyetteredhat

# [OSIDB-ID] [Title]

## Checklist:

- [ ] Linting passed
- [ ] Type checks passed
- [ ] Tests suite passed
- [ ] Commits consolidated
- [ ] Changelog updated
- [ ] Test cases added/updated
- [ ] Jira ticket updated

## Summary:

OSIDB-2876:  Add new affected component button
OSIDB-2533: Sort affects by product family, alphabetical

## Changes:

## Considerations:

2024-06-11 08:55 UTC, C-Valen reviewed
Some suggestions for possible UI/UX improvements:
- Make buttons a bit smaller so they are consistent with other buttons in the section (e.g. same size as expand/collapse, file tracker etc.)
- Auto expand added modules and components
- When adding a component, all other modules remain in same collapsed/expanded state. (currently all other expanded modules are collapsed when a new module is added)

2024-06-11 12:06 UTC, tboyetteredhat commented
> Some suggestions for possible UI/UX improvements:
> 
> * Make buttons a bit smaller so they are consistent with other buttons in the section (e.g. same size as expand/collapse, file tracker etc.)
> * Auto expand added modules and components
> * When adding a component, all other modules remain in same collapsed/expanded state. (currently all other expanded modules are collapsed when a new module is added)

Thanks for your feedback. I will fix those issues.

2024-06-25 13:25 UTC, C-Valen reviewed
I think we could avoid using modules names for indexing. 

It also would be nice to validate names so the users get a feedback for example when they are using a name that already exists (even in draft module) before saving or when the module name is empty.

Minimum relevance but the position for the module name field feels a bit of unnatural to me, I would have preference to have it inside the collapse (if there are not drawbacks). I wonder if would it be easy to just make the module name editable when clicked, and on blur saving it and make it static, avoiding that way the use of additional fields and space.

2024-06-26 15:47 UTC, tboyetteredhat commented on src/components/AffectedOfferings.vue
> +  'update-module-name': [previousModuleName: string, newModuleName: string];
I think if we update moduleName, we need to update all affects under that moduleName. Those affects are un saved in OSIDB and just new affects

2024-06-26 16:13 UTC, superbuggy requested changes

2024-06-26 16:13 UTC, superbuggy commented on src/composables/useFlawAffectsModel.ts
> +  function addBlankAffect(moduleName: string, callback: (affect: ZodAffectType) => void) {
```suggestion
  function addBlankAffect(): ZodAffectType {
    const embargoed = flaw.value.embargoed;
    flaw.value.affects.push({
      embargoed,
      affectedness: '',
      resolution: '',
      delegated_resolution: '', // should this be null
      ps_module: '',
      ps_component: '',
      impact: '',
      cvss_scores: [{
        // affect: z.string().uuid(),
        cvss_version: 'V3',
        issuer: 'RH',
        comment: '',
        score: null,
        vector: '',
        embargoed,
        alerts: [],
      }],
      trackers: [{ errata: [] }],
      alerts: [],
    } as ZodAffectType);
    return flaw.value.affects.at(-1);
  }
```

2024-06-26 16:13 UTC, superbuggy commented on src/composables/useFlawAffectsModel.ts
> +  function addBlankAffect(moduleName: string, callback: (affect: ZodAffectType) => void) {
This would avoid having to add a callback by just returning the new affect that was just added to the flaw's list of affects, this should be reactive

2024-06-26 16:13 UTC, superbuggy commented on src/components/AffectedOfferings.vue
> +  expandedModules.value[newModuleName] = true;
here you could just call the modified `addBlankAffect` function (outlined below, the change being to return the new blank affect) and modify the `.ps_module` property of the affect.

2024-07-04 13:58 UTC, MrMarble commented
Could you add some screenshots or a video, maybe to the jira ticket, to understand the changes better?

2024-07-10 18:22 UTC, superbuggy commented
@tboyetteredhat and I had a call and it seemed like the best course of action might be to split these issues up and to handle sorting separately from changing the affects UI which @C-Valen is redesigning--there may be a way to avoid the user having to deal with the screen jumping around when the affect's module and component are set (a consequence of the sorting of affects)

2024-07-10 18:24 UTC, closed without merging