OSIDB-2899: Rename Flaw Status to Flaw State in Advanced search
RedHatProductSecurity/osim pull request #267
Opened 2024-06-12 08:47 UTC by MrMarble

# [OSIDB-2899] Rename Flaw Status to Flaw State in Advanced search

## Checklist:

- [ ] Linting passed
- [ ] Type checks passed
- [ ] Tests suite passed
- [ ] Commits consolidated
- [ ] Changelog updated
- [ ] Test cases added/updated
- [ ] Jira ticket updated

## Summary:

In advanced searching we call it "flaw status", in the api we call it "state" and in the detail page we call it "state". So we should update the advanced search field to call it "State".

|Before|After|
|---|---|
|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/4a3d642f-6e23-459b-8659-1a8ac5dba5f5)|![image](https://github.com/RedHatProductSecurity/osim/assets/4268580/15f51fc0-77e2-4681-a7c7-c0059e58da9a)|

2024-06-12 13:54 UTC, tboyetteredhat requested changes

2024-06-12 13:54 UTC, tboyetteredhat commented on src/components/IssueQueue.vue
> -    cwe_id: 'CWE ID',
any reason for removing this field?

2024-06-12 13:56 UTC, tboyetteredhat commented on src/components/IssueQueue.vue
> -    cwe_id: 'CWE ID',
We don't need to remove cwe_id.

2024-06-13 13:58 UTC, MrMarble commented on src/components/IssueQueue.vue
> -    cwe_id: 'CWE ID',
Good catch! That was a total mistake 🤦🏼

2024-06-13 14:02 UTC, tboyetteredhat approved these changes

2024-06-13 15:09 UTC, d10n approved these changes

2024-06-13 15:13 UTC, superbuggy approved these changes

2024-06-13 15:15 UTC, C-Valen approved these changes

2024-06-13 15:53 UTC, merged