✨ Provide label for unembargoed flaws
RedHatProductSecurity/osim pull request #315
Opened 2024-06-25 19:03 UTC by superbuggy

# OSIDB-2937 Confusing Embargo badges

## Checklist:

- [x] Linting passed
- [x] Type checks passed
- [x] Tests suite passed
- [x] Commits consolidated
- [ ] Changelog updated
- [-] Test cases added/updated
- [x] Jira ticket updated

## Summary:
<img width="1056" alt="image" src="https://github.com/RedHatProductSecurity/osim/assets/17716232/5529d7ee-9516-45f9-85e0-00e288bb34f9">

## Changes:

- Provide badge for unembargoed flaws 
- Prevent edge case embargo label showing when flaw isn't embargoed (invalid data)

## Considerations:

[Replace with any additional considerations, notes, or instructions for reviewers.]

2024-06-26 13:11 UTC, JakubFrejlach commented on src/components/IssueQueueItem.vue
> +);
I am just thinking, why does this logic needs to be so complicated?
`Flaw.embargoed == true` -> embargoed 
`Flaw.embargoed == false` -> unembargoed (public)

Or am I missing something?

2024-06-26 13:21 UTC, JakubFrejlach requested changes
I am just thinking, why does this logic needs to be so complicated?
`Flaw.embargoed == true` -> embargoed 
`Flaw.embargoed == false` -> unembargoed (public)

Or am I missing something? I don't think anything with the dates is not needed for the logic.

2024-06-26 14:34 UTC, superbuggy commented on src/components/IssueQueueItem.vue
> + && DateTime.fromISO(props.issue.unembargo_dt).diffNow().milliseconds <= 0
```suggestion
const isUnembargoed = computed(() => DateTime.fromISO(props.issue.unembargo_dt).diffNow().milliseconds <= 0
```

2024-06-26 14:43 UTC, superbuggy commented
> I am just thinking, why does this logic needs to be so complicated? `Flaw.embargoed == true` -> embargoed `Flaw.embargoed == false` -> unembargoed (public)
> 
> Or am I missing something? I don't think anything with the dates is not needed for the logic.

I'm not really sure about this PR, tbh--it stemmed from a presumably transient data integrity issue specific to one environment. Do you think there is a need for an Unembargoed label?

2024-06-27 06:57 UTC, JakubFrejlach commented
> > I am just thinking, why does this logic needs to be so complicated? `Flaw.embargoed == true` -> embargoed `Flaw.embargoed == false` -> unembargoed (public)
> > Or am I missing something? I don't think anything with the dates is not needed for the logic.
> 
> I'm not really sure about this PR, tbh--it stemmed from a presumably transient data integrity issue specific to one environment. Do you think there is a need for an Unembargoed label?

Can you please elaborate a little bit? I don't quite follow about the integrity issue. Also I don't think the label unembargoed is really needed, every Flaw is either emabrgoed or unembargoed, so either embargoed label or no label should be enough, right?

2024-06-27 14:07 UTC, superbuggy commented
Okay, if that's the single source of truth then yes. Upadted lmk if it looks good @JakubFrejlach

2024-06-27 14:38 UTC, MrMarble approved these changes

2024-06-27 14:39 UTC, d10n approved these changes

2024-06-27 14:39 UTC, merged