Allow deleting CVSS scores
RedHatProductSecurity/osim pull request #343
Opened 2024-07-08 11:26 UTC by dmonzonis

# OSIDB-1843 Allow deleting CVSS scores

Right now it is not possible to delete a flaw's CVSS score through OSIM. Even though there is a button to clear the field, when trying to save the flaw it will show an error saying that this field cannot be null.

With this commit, when clearing the CVSS score field and saving the flaw, it will delete the CVSS score through OSIDB's API, using the DELETE method.

Closes OSIDB-1843.

## Checklist:

- [ ] Linting passed
- [ ] Type checks passed
- [ ] Tests suite passed
- [ ] Commits consolidated
- [ ] Changelog updated
- [ ] Test cases added/updated
- [ ] Jira ticket updated

## Summary:

[Replace with a brief summary of the changes introduced by this PR.]

## Changes:

[Replace with a detailed description of the changes made in this PR, including any new features, enhancements, bug fixes, or refactorings.]

## Considerations:

[Replace with any additional considerations, notes, or instructions for reviewers.]

2024-07-11 14:49 UTC, C-Valen approved these changes

2024-07-11 14:49 UTC, superbuggy requested changes

2024-07-11 14:49 UTC, superbuggy commented on src/composables/useFlawCvssScores.ts
> +      if (flawRhCvss3.value?.vector === null && flawRhCvss3.value?.uuid !== null) {
```suggestion
      if (flawRhCvss3.value?.vector === null && flawRhCvss3.value?.uuid != null) {
```

2024-07-11 14:49 UTC, superbuggy commented on src/composables/useFlawCvssScores.ts
> +      if (flawRhCvss3.value?.vector === null && flawRhCvss3.value?.uuid !== null) {
`!=` will allow undefined, which likely would be the value if the cvss data were not saved

2024-07-15 09:53 UTC, MrMarble approved these changes

2024-07-17 14:25 UTC, superbuggy approved these changes

2024-07-17 14:25 UTC, merged