OSIM: CVSS Rescoring Workflow (Email NIST)
RedHatProductSecurity/osim pull request #67
Opened 2024-02-21 18:36 UTC by tboyetteredhat

2024-02-28 19:43 UTC, d10n commented
Approved pending test update

2024-03-05 16:31 UTC, superbuggy requested changes
This looks great, the tests are really thorough! Just 2 very minor changes requested

2024-03-05 16:31 UTC, superbuggy commented on src/components/CvssNISTForm.vue
> +  const recipient = encodeURI('nvd@nist.gov');
use `toEmail` here

2024-03-05 16:31 UTC, superbuggy commented on src/components/CvssNISTForm.vue
> +  const cc = encodeURI('secalert@redhat.com');
use `ccEmail` here

2024-03-05 16:48 UTC, tboyetteredhat commented on src/components/CvssNISTForm.vue
> +  const recipient = encodeURI('nvd@nist.gov');
updated

2024-03-05 16:48 UTC, tboyetteredhat commented on src/components/CvssNISTForm.vue
> +  const cc = encodeURI('secalert@redhat.com');
updated

2024-03-05 17:59 UTC, merged